name: Build and Test GitHub Release Manager

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ]
      fail-fast: false

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            target/
          key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}

      - name: Build with Maven
        run: mvn clean package

      - name: Verify JAR Creation
        run: |
          ls target/

      - name: Test Installation Command
        run: |
          java -jar ./target/github-releases-manager-1.0-SNAPSHOT-jar-with-dependencies.jar install keepassxreboot/keepassxc


      - name: Verify Installation (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          echo "Ubuntu: Checking installed files..."
          ls -la ~/.local/bin

      - name: Verify Installation (MacOS)
        if: matrix.os == 'macos-latest'
        run: |
          echo "Checking installed files..."
          ls -la /Applications
          echo "Checking mount dir..."
          ls -la ~/Volumes
          echo "Checking config file..."
          ls -la "~/Library/Application Support/"


      - name: Test list (MacOS)
        if: matrix.os == 'macos-latest'
        run: |
            java -jar ./target/github-releases-manager-1.0-SNAPSHOT-jar-with-dependencies.jar list

      - name: Test uninstall (MacOS)
        if: matrix.os == 'macos-latest'
        run: |
            java -jar ./target/github-releases-manager-1.0-SNAPSHOT-jar-with-dependencies.jar uninstall keepassxreboot/keepassxc

      - name: Test list after uninstall (MacOS)
        if: matrix.os == 'macos-latest'
        run: |
            java -jar ./target/github-releases-manager-1.0-SNAPSHOT-jar-with-dependencies.jar list

      - name: Verify post-uninstallation (MacOS)
        if: matrix.os == 'macos-latest'
        run: |
          echo "Checking installed files..."
          ls -la /Applications
          echo "Checking mount dir..."
          ls -la ~/Volumes
          echo "Checking config file..."
          ls -la ~/Library/Application\ Support/

      - name: Upload Artifacts on Failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: error-logs-${{ matrix.os }}
          path: |
            target/
            **/surefire-reports/
            **/failsafe-reports/